version: '3.8'

services:
  front:
    image: example-frontend
    ports:
      - 5000:5000
  back:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000 