version: '3.8'

services:
  redis:
    image: redis:7-alpine
  front:
    image: example-frontend
    ports:
      - 5000:5000
  back:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis