version: '3.8'

services:
  redis:
    image: redis:7-alpine
  postgresdb:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=rkvin123
      - POSTGRES_PASSWORD=rkvin123
      - POSTGRES_DATABASE=postgres
  front:
    image: example-frontend
    ports:
      - 5000:5000
  back:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - POSTGRES_HOST=postgresdb
      - POSTGRES_USER=rkvin123
      - POSTGRES_PASSWORD=rkvin123
      - POSTGRES_DATABASE=postgres
      - REDIS_HOST=redis